### ISSUE TITLE
Update boost in 74x

### ISSUE THREAD

**Issue by davidlange6** [cms-sw/cmsdist#1501]
Hi @degano @nclopezo  - could you update boost in 74x to be the same as 73x (1.57) - would be great if in time for the 1100 IB today.

Thx-

**Comment by nclopezo** [comment]
Hi David,
I did it here: https://github.com/cms-sw/cmsdist/pull/1504

**Comment by nclopezo** [comment]
I noticed that because of the automatic forward ports, the changes ended also in 7_5_X, do you want me to revert it in the 75X IBs?

**Comment by davidlange6** [comment]
Hi David
I think 75x is fine.

**Comment by davidlt** [comment]
I was about to build a local build of CMSSW using `IB/CMSSW_7_5_X/stable`, which is broken now. Crappy foward-porting left it in a mixed state.

**Comment by davidlt** [comment]
Looks like `IB/CMSSW_7_4_X/root6` is also broken. The changed were done to `IB/CMSSW_7_4_X/stable`, but other branches had changed to `boost.spec` at least. I see one hunk left in `boost.spec`.

**Comment by davidlt** [comment]
I fixed the problem in `IB/CMSSW_7_5_X/stable` and `IB/CMSSW_7_4_X/root6`. @nclopezo could you relaunch the IBs?

**Comment by smuzaffar** [comment]
I have restarted the failed IBs.

**Comment by smuzaffar** [comment]
75X/root5 is still broken

ERROR! File not found: /build/cmsbuild/jenkins-workarea/workspace/build-cache/cms.week1/CMSDIST/boost-1.47.0-fix-strict-overflow.patch

can you fix that one too

**Comment by davidlt** [comment]
@smuzaffar done, try again.

**Comment by nclopezo** [comment]
Thanks, I was going to fix it after lunch. I confirm that 75root5 is in the Jenkins queue.
